@startuml C4_Component_UserService
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Container(userService, "User Service", "Go", "ћикросервис дл€ управлени€ пользовател€ми")

Component(userApi, "User API", "REST", "операции с пользовател€ми")
Component(userManager, "User Manager", "Go", "—оздание, обновление, удаление пользователей")
Component(userDB, "User DB", "PostgreSQL", "’ранение данных пользователей")

Rel(userApi, userManager, "ќбрабатывает запросы")
Rel(userManager, userDB, "„тение/запись", "SQL")

@enduml
