@startuml C4_Component_DeviceService
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Container(deviceService, "Device Control Service", "Go", "Микросервис для управления устройствами")

Component(deviceApi, "Device API", "REST", "Принимает команды и запросы от пользователей/сервисов")
Component(commandHandler, "Command Handler", "Go", "Обрабатывает команды, проверяет входные данные")
Component(deviceManager, "Device Manager", "Go", "Бизнес-логика управления состоянием устройств")
Component(deviceRepo, "Device Repository", "DAO/Postgres", "Хранение и получение данных об устройствах")
Component(eventPublisher, "Event Publisher", "Kafka/RabbitMQ", "Публикует события о действиях с устройствами")

Rel(deviceApi, commandHandler, "Передаёт команды")
Rel(commandHandler, deviceManager, "Выполняет команду")
Rel(deviceManager, deviceRepo, "id для устройств")
Rel(deviceManager, eventPublisher, "Отправка событий")


@enduml
