@startuml C4_Component_TelemetryService
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Container(telemetryService, "Telemetry Service", "Go", "Микросервис для приёма, обработки и хранения данных телеметрии")

Component(telemetryIngestion, "Telemetry Ingestion", "Kafka/RabbitMQ Consumer", "Подписка на очередь, получение данных от gateway-service")
Component(dataProcessor, "Data Processor", "Go", "Валидация и обработка телеметрии, агрегации")
Component(telemetryRepo, "Telemetry Repository", "TimescaleDB/InfluxDB", "Хранение данных телеметрии (временные ряды)")
Component(telemetryApi, "Telemetry API", "REST/gRPC", "Предоставление данных другим сервисам и пользователям")
Component(alertManager, "Alert Manager", "Go", "Уведомления при аномалиях (низкая температура, перегрузка и т.д.)")

Rel(telemetryIngestion, dataProcessor, "Передаёт данные")
Rel(dataProcessor, telemetryRepo, "Сохраняет результаты")
Rel(telemetryApi, telemetryRepo, "Читает данные", "SQL/TSDB API")
Rel(dataProcessor, alertManager, "Генерирует события при аномалиях")
Rel(telemetryIngestion, telemetryService, "Получает данные из", "Kafka/RabbitMQ")

@enduml
