@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/refs/heads/master/C4_Context.puml

Person(user, "Клиент")
Person(engineer, "Выездной специалист", "Подключает новые устройства")
System(warmhouse, "Система «Теплый дом»")
System_Ext(sensor, "Подключенное устройство")

Rel(user, warmhouse, "Просматривает и управляет устройствами")
Rel(warmhouse, sensor, "Посылает команды и запрашивает состояние")
Rel(engineer, sensor, "Регистрирует в системе")
Rel(engineer, warmhouse, "Подключает новое устройство")

@enduml