openapi: 3.0.3
info:
  title: Access Service API
  version: 1.0.0
servers:
  - url: http://access-service:8080/api/v1
paths:
  /access/permissions:
    get:
      summary: List all permissions
      responses:
        "200":
          description: Permission list
    post:
      summary: Grant permission
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [userId, deviceId, role]
              properties:
                userId: { type: string }
                deviceId: { type: string }
                role: { type: string }
      responses:
        "201": { description: Permission granted }
  /access/permissions/{id}:
    delete:
      summary: Revoke permission
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        "204": { description: Revoked }
