openapi: 3.0.3
info:
  title: Auth Service API
  version: 1.0.0
servers:
  - url: http://auth-service:8080/api/v1
paths:
  /auth/login:
    post:
      summary: Login user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email: { type: string }
                password: { type: string }
      responses:
        "200":
          description: JWT token
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token: { type: string }
                  refresh_token: { type: string }
  /auth/logout:
    post:
      summary: Logout user
      responses:
        "204": { description: Logged out }
