openapi: 3.0.3
info:
  title: Device Control Service API
  version: 1.0.0

servers:
  - url: http://device-service:8080/api/v1

paths:
  /control/commands:
    post:
      summary: Send command to a device
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                deviceId:
                  type: integer
                  description: Device id
                command:
                  type: string
                  description: Command ("ON", "OFF"...)
                parameters:
                  type: object
                  description: Optional parameters
              required:
                - deviceId
                - command
      responses:
        "200":
          description: ok
        "400":
          description: Invalid data
        "404":
          description: Device not found
