openapi: 3.0.3
info:
  title: User Service API
  version: 1.0.0
servers:
  - url: http://user-service:8080/api/v1
paths:
  /users:
    get:
      summary: List users
      responses:
        "200":
          description: Users list
          content:
            application/json:
              schema:
                type: array
                items: { $ref: "#/components/schemas/User" }
    post:
      summary: Create user
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/UserCreate" }
      responses:
        "201":
          description: User created
  /users/{id}:
    get:
      summary: Get user by ID
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        "200": { description: User object }
    put:
      summary: Update user
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      requestBody:
        content:
          application/json:
            schema: { $ref: "#/components/schemas/UserUpdate" }
      responses:
        "200": { description: User updated }
    delete:
      summary: Delete user
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        "204": { description: Deleted }
components:
  schemas:
    User:
      type: object
      properties:
        id: { type: string }
        email: { type: string }
        name: { type: string }
        createdAt: { type: string, format: date-time }
    UserCreate:
      type: object
      required: [email, name, password]
      properties:
        email: { type: string }
        name: { type: string }
        password: { type: string }
    UserUpdate:
      type: object
      properties:
        name: { type: string }
        password: { type: string }
